# SPDX-FileCopyrightText: 2026 sFOX and contributors <https://github.com/sfoxhq/ash_versioned/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

spark_locals_without_parens = [
  action: 1,
  allow_forbidden_field?: 1,
  allow_nil?: 1,
  archive: 0,
  archive: 1,
  archive: 2,
  attribute: 1,
  attribute_always_select?: 1,
  attribute_public?: 1,
  attribute_type: 1,
  attribute_writable?: 1,
  authorize_read_with: 1,
  belongs_to_actor: 2,
  belongs_to_actor: 3,
  belongs_to_versioned: 2,
  belongs_to_versioned: 3,
  could_be_related_at_creation?: 1,
  create_timestamp_attribute: 1,
  default_sort: 1,
  define_attribute?: 1,
  description: 1,
  destination_attribute: 1,
  domain: 1,
  exclude_read_actions: 1,
  exclude_update_actions: 1,
  filter: 1,
  filter: 2,
  filterable?: 1,
  from_many?: 1,
  has_many_versioned: 2,
  has_many_versioned: 3,
  has_one_versioned: 2,
  has_one_versioned: 3,
  history_action: 1,
  identity: 0,
  identity: 1,
  identity: 2,
  latest: 0,
  latest: 1,
  latest: 2,
  limit: 1,
  manual: 1,
  name: 1,
  no_attributes?: 1,
  not_found_message: 1,
  offset: 1,
  on_delete: 1,
  origin: 1,
  primary_key?: 1,
  public?: 1,
  read_action: 1,
  read_action_arguments: 1,
  reference_actor: 1,
  reference_actor: 2,
  relationship_context: 1,
  sort: 1,
  sortable?: 1,
  source: 1,
  source_attribute: 1,
  source_prefix: 1,
  temporal_keys: 1,
  through: 1,
  transform: 1,
  type: 1,
  unarchive: 1,
  update_timestamp_attribute: 1,
  validate_destination_attribute?: 1,
  version: 0,
  version: 1,
  version: 2,
  violation_message: 1,
  writable?: 1
]

[
  import_deps: [:ash, :ash_postgres],
  inputs: ["{mix,.formatter,.credo}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  plugins: [Spark.Formatter, Quokka],
  locals_without_parens: spark_locals_without_parens,
  export: [
    locals_without_parens: spark_locals_without_parens
  ]
]
