# SPDX-FileCopyrightText: 2026 sFOX and contributors <https://github.com/sfoxhq/ash_versioned/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

defmodule AshVersionedTest.LinkedWidget do
  @moduledoc """
  Resource testing a plain (Ash-core) `belongs_to`, as opposed to `belongs_to_actor`.
  The `owner_id` is generated by `Ash.Resource.Transformers.BelongsToAttribute`, not by
  `AshVersioned.Transformers.AddFields`.
  """

  use Ash.Resource,
    domain: AshVersionedTest.Domain,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshVersioned.Resource]

  alias AshVersionedTest.Repo
  alias AshVersionedTest.User

  postgres do
    table "linked_widgets"
    repo Repo
  end

  versioning do
  end

  relationships do
    belongs_to :owner, User, public?: true, writable?: true
  end

  actions do
    defaults [:read]

    create :create do
      accept [:status, :owner_id]
    end

    update :increment do
      accept [:status]
    end
  end

  attributes do
    integer_primary_key :id
    attribute :status, :string, public?: true, allow_nil?: false
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end
end
